Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2022-07, with the labels that each got.

#326 ESP32 core 2.0.4 CI fixes
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloudTCP.cpp
  src/cbor/lib/tinycbor/src/open_memstream.c
  src/utility/watchdog/Watchdog.cpp
Labels: topic: code

#323 Add some notes in the README about ESP devices
  README.md
Labels: type: enhancement, topic: documentation

#322 Add esp32 architecture in library.properties file
  library.properties
Labels: type: imperfection, topic: infrastructure

#316 Remove ArduinoBearSSL as a CI build dependency.
  .github/workflows/compile-examples.yml
  examples/utility/SelfProvisioning/ECCX08Cert.cpp
Labels: type: enhancement, topic: code
