Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2022-09, with the labels that each got.

#333 CI: Use mbed_portenta core release instead of ArduinoCore-mbed HEAD
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#332 Fix spell check failures and typos
  .codespellrc
  README.md
  examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
  examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
  examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
  examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
  examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
  examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
  examples/utility/Provisioning/Provisioning.ino
  extras/test/src/test_CloudLocation.cpp
  extras/test/src/test_CloudSchedule.cpp
  extras/test/src/test_publishOnChange.cpp
  extras/test/src/test_publishOnChangeRateLimit.cpp
  extras/test/src/test_readOnly.cpp
  extras/test/src/test_writeOnly.cpp
  library.properties
  src/ArduinoIoTCloudTCP.cpp
  src/cbor/CBOREncoder.cpp
  src/utility/ota/OTA-samd.cpp
Labels: type: imperfection, topic: documentation, topic: infrastructure

#334 Fix Unexpected input warning running unit-tests workflow
  .github/workflows/unit-tests.yml
Labels: type: enhancement, topic: infrastructure

#335 Add common define for STM32H7 boards
  src/AIoTC_Config.h
  src/ArduinoIoTCloudTCP.cpp
  src/utility/ota/OTA-portenta-h7.cpp
  src/utility/ota/OTA.h
  src/utility/watchdog/Watchdog.cpp
Labels: type: enhancement, topic: code
