Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2022-01, with the labels that each got.

#296 Add GitHub Actions workflow to synchronize with shared repository labels
  .github/workflows/sync-labels.yml
Labels: enhancement

#298 Add retry delay on topic subscription failures
  src/AIoTC_Config.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
Labels: topic: code

#293 Avoid multivalue properties split
  extras/test/src/test_encode.cpp
  extras/test/src/util/CBORTestUtil.cpp
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloud.h
  src/ArduinoIoTCloudLPWAN.cpp
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/cbor/CBOREncoder.cpp
  src/cbor/CBOREncoder.h
  src/cbor/lib/tinycbor/cbor-lib.h
  src/cbor/lib/tinycbor/src/cbor.h
  src/cbor/lib/tinycbor/src/cborerrorstrings.c
  src/property/Property.cpp
  src/property/Property.h
  src/property/PropertyContainer.cpp
  src/property/types/CloudColor.h
  src/property/types/CloudLocation.h
  src/property/types/CloudSchedule.h
  src/property/types/automation/CloudColoredLight.h
  src/property/types/automation/CloudDimmedLight.h
  src/property/types/automation/CloudTelevision.h
Labels: type: imperfection, topic: code
