Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2023-06, with the labels that each got.

#365 Add support for PORTENTA C33
  src/AIoTC_Config.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/utility/time/TimeService.cpp
Labels: type: enhancement, topic: code

#362 Configuration: Add BOARD_HAS_SECRET_KEY
  examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
  examples/ArduinoIoTCloud-Advanced/thingProperties.h
  examples/ArduinoIoTCloud-Basic/arduino_secrets.h
  examples/ArduinoIoTCloud-Basic/thingProperties.h
  examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
  examples/ArduinoIoTCloud-Callbacks/thingProperties.h
  examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
  examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
  examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
  examples/ArduinoIoTCloud-Schedule/thingProperties.h
  examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
  examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
  src/AIoTC_Config.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
Labels: type: enhancement, topic: code

#367 Enable compile example workflow for Portenta C33
  .github/workflows/compile-examples.yml
  library.properties
Labels: type: enhancement, topic: infrastructure

#368 Use token when uploading unit test code coverage data to Codecov from workflow
  .github/workflows/unit-tests.yml
Labels: type: imperfection, topic: infrastructure
