Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2024-05, with the labels that each got.

#428 chore: Switch LPWAN off deprecated method
  src/AIoTC_Config.h
  src/ArduinoIoTCloudLPWAN.cpp
  src/property/PropertyContainer.cpp
Labels: type: imperfection, topic: code

#440 Remove public functions to handle thing_id and timezone
  extras/test/CMakeLists.txt
  extras/test/src/test_writeOnChange.cpp
  extras/test/src/test_writeOnDemand.cpp
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloud.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/property/Property.cpp
  src/property/Property.h
  src/property/PropertyContainer.cpp
Labels: type: enhancement, topic: code

#456 Unify how timeouts are handled for TCP state machine
  src/AIoTC_Config.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/utility/time/TimedAttempt.cpp
  src/utility/time/TimedAttempt.h
Labels: type: enhancement, topic: code

#442 Move properties containers inside class implementation
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloud.h
  src/ArduinoIoTCloudLPWAN.cpp
  src/ArduinoIoTCloudLPWAN.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
Labels: type: enhancement, topic: code

#443 New cloud interfaces
  src/interfaces/CloudProcess.h
  src/interfaces/MessageStream.h
  src/message/Commands.h
Labels: type: enhancement, topic: code

#444 New thing process
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloud.h
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/ArduinoIoTCloudThing.cpp
  src/ArduinoIoTCloudThing.h
  src/utility/time/TimeService.h
Labels: type: enhancement, topic: code

#459 Fix thing property reconfiguration after wifi loss
  src/ArduinoIoTCloudTCP.cpp
Labels: type: imperfection, topic: code

#461 Debug: print mqttClient error code when connection fails
  src/ArduinoIoTCloudTCP.cpp
Labels: type: enhancement, topic: code

#447 Add new Command topics
  extras/test/CMakeLists.txt
  extras/test/src/test_command_decode.cpp
  extras/test/src/test_command_encode.cpp
  src/ArduinoIoTCloudDevice.cpp
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/cbor/CBOR.cpp
  src/cbor/CBOR.h
  src/cbor/MessageDecoder.cpp
  src/cbor/MessageDecoder.h
  src/cbor/MessageEncoder.cpp
  src/cbor/MessageEncoder.h
  src/interfaces/Decoder.h
  src/interfaces/Encoder.h
  src/message/Commands.h
Labels: type: enhancement, topic: code

#448 Add mTLS support for OTA file download
  src/AIoTC_Config.h
  src/tls/AIoTCUPCert.h
  src/tls/BearSSLClient.cpp
  src/tls/BearSSLClient.h
  src/tls/BearSSLTrustAnchors.h
  src/tls/utility/TLSClientMqtt.cpp
  src/tls/utility/TLSClientMqtt.h
  src/tls/utility/TLSClientOta.cpp
  src/tls/utility/TLSClientOta.h
Labels: type: enhancement, topic: code

#449 New ota structure
  .github/workflows/compile-examples.yml
  library.properties
  src/AIoTC_Config.h
  src/ArduinoIoTCloudDevice.cpp
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudTCP.h
  src/ota/OTA.h
  src/ota/OTAConfig.h
  src/ota/OTATypes.h
  src/ota/implementation/OTAEsp32.cpp
  src/ota/implementation/OTAEsp32.h
  src/ota/implementation/OTANanoRP2040.cpp
  src/ota/implementation/OTANanoRP2040.h
  src/ota/implementation/OTASTM32H7.cpp
  src/ota/implementation/OTASTM32H7.h
  src/ota/implementation/OTASamd.cpp
  src/ota/implementation/OTASamd.h
  src/ota/implementation/OTAUnoR4.cpp
  src/ota/implementation/OTAUnoR4.h
  src/ota/interface/OTAInterface.cpp
  src/ota/interface/OTAInterface.h
  src/ota/interface/OTAInterfaceDefault.cpp
  src/ota/interface/OTAInterfaceDefault.h
  src/utility/lzss/lzss.cpp
  src/utility/lzss/lzss.h
  src/utility/ota/FlashSHA256.cpp
  src/utility/ota/FlashSHA256.h
  src/utility/ota/OTA-esp32.cpp
  src/utility/ota/OTA-nano-rp2040.cpp
  src/utility/ota/OTA-portenta-h7.cpp
  src/utility/ota/OTA-samd.cpp
  src/utility/ota/OTA-unor4.cpp
  src/utility/ota/OTA.cpp
  src/utility/ota/OTA.h
Labels: type: enhancement, topic: code

#451 Add detach and update timezone commands
  extras/test/src/test_command_decode.cpp
  extras/test/src/test_command_encode.cpp
  src/ArduinoIoTCloudTCP.cpp
  src/ArduinoIoTCloudThing.cpp
  src/ArduinoIoTCloudThing.h
  src/cbor/CBOR.cpp
  src/cbor/CBOR.h
  src/cbor/MessageDecoder.cpp
  src/cbor/MessageDecoder.h
  src/message/Commands.h
Labels: type: enhancement, topic: code

#470 Delete nullptr check on local fixed size array
  src/ota/implementation/OTAEsp32.cpp
Labels: topic: code

#469 fix: Warnings
  src/utility/time/TimeService.cpp
Labels: type: imperfection, topic: code
