Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2024-02, with the labels that each got.

#417 Configure Dependabot to check for outdated actions used in workflows
  .github/dependabot.yml
Labels: type: enhancement, topic: infrastructure

#423 Fix regression re report-size-deltas after updating actions/upload-artifact.
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#403 Use DEFAULT_MIN_TIME_BETWEEN_UPDATES_MILLIS as default period for publishOnChange
  extras/test/src/test_publishOnChange.cpp
  src/property/Property.h
Labels: type: imperfection, topic: code

#404 Add build configuration file for ECCX08
  src/AIoTC_Config.h
  src/ArduinoECCX08Config.h
Labels: type: enhancement, topic: code

#406 Avoid library to call deprecated functions itself
  src/ArduinoIoTCloud.cpp
  src/ArduinoIoTCloud.h
Labels: type: imperfection, topic: code

#412 Make examples build on cloud web editor
  examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
  examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
  examples/ArduinoIoTCloud-Advanced/thingProperties.h
  examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
  examples/ArduinoIoTCloud-Basic/arduino_secrets.h
  examples/ArduinoIoTCloud-Basic/thingProperties.h
  examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
  examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
  examples/ArduinoIoTCloud-Callbacks/thingProperties.h
  examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
  examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
  examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
  examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
  examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
  examples/ArduinoIoTCloud-Schedule/thingProperties.h
  examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
  examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
  examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
Labels: type: imperfection, topic: documentation

#429 Fix regression: report size delta size on PR.
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
  .gitignore
Labels: type: imperfection, topic: infrastructure

#430 Fix size deltas report infrastructure configuration
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
Labels: type: imperfection, topic: infrastructure

#431 Update report-size-deltas workflow to wake him up
  .github/workflows/report-size-deltas.yml
  src/ArduinoIoTCloudTCP.cpp
Labels: topic: infrastructure

#432 OTA: changing download to downloadAndDecompress for mbed core
  src/utility/ota/OTA-portenta-h7.cpp
Labels: type: enhancement, topic: code
