Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2024-11, with the labels that each got.

#510 Add "Block for OTA" example
  examples/ArduinoIoTCloud-BlockForOTA/ArduinoIoTCloud-BlockForOTA.ino
  examples/ArduinoIoTCloud-BlockForOTA/arduino_secrets.h
  examples/ArduinoIoTCloud-BlockForOTA/thingProperties.h
Labels: type: enhancement, topic: documentation

#511 ArduinoCloudTCP: print BearSSL error code
  src/ArduinoIoTCloudTCP.cpp
Labels: topic: code

#505 RP2040 Connect OTA fix appSize computation with cores using PRNG
  src/ota/implementation/OTANanoRP2040.cpp
Labels: type: imperfection, topic: code

#514 Fix ota download byte count
  src/ota/interface/OTAInterfaceDefault.cpp
Labels: type: imperfection, topic: code
