Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2024-04, with the labels that each got.

#426 chore: clean examples
  examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
  examples/ArduinoIoTCloud-Advanced/thingProperties.h
  examples/ArduinoIoTCloud-Basic/arduino_secrets.h
  examples/ArduinoIoTCloud-Basic/thingProperties.h
  examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
  examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
  examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
  examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
  examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
  examples/ArduinoIoTCloud-Schedule/thingProperties.h
Labels: type: imperfection, type: enhancement, topic: documentation

#438 fix: Await Serial
  examples/ArduinoIoTCloud-Advanced/ArduinoIoTCloud-Advanced.ino
  examples/ArduinoIoTCloud-Basic/ArduinoIoTCloud-Basic.ino
  examples/ArduinoIoTCloud-Callbacks/ArduinoIoTCloud-Callbacks.ino
  examples/ArduinoIoTCloud-DeferredOTA/ArduinoIoTCloud-DeferredOTA.ino
  examples/ArduinoIoTCloud-Schedule/ArduinoIoTCloud-Schedule.ino
  examples/utility/ArduinoIoTCloud_Travis_CI/ArduinoIoTCloud_Travis_CI.ino
Labels: type: imperfection, topic: documentation

#437 Add setThingId call in Travic_CI sketch to ensure checking function existance
  examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
Labels: type: enhancement, topic: infrastructure

#450 Examples: Avoid SECRET_PASS redefinition on Portenta H7
  examples/ArduinoIoTCloud-Advanced/arduino_secrets.h
  examples/ArduinoIoTCloud-Advanced/thingProperties.h
  examples/ArduinoIoTCloud-Basic/arduino_secrets.h
  examples/ArduinoIoTCloud-Basic/thingProperties.h
  examples/ArduinoIoTCloud-Callbacks/arduino_secrets.h
  examples/ArduinoIoTCloud-Callbacks/thingProperties.h
  examples/ArduinoIoTCloud-DeferredOTA/arduino_secrets.h
  examples/ArduinoIoTCloud-DeferredOTA/thingProperties.h
  examples/ArduinoIoTCloud-Schedule/arduino_secrets.h
  examples/ArduinoIoTCloud-Schedule/thingProperties.h
  examples/utility/ArduinoIoTCloud_Travis_CI/arduino_secrets.h
  examples/utility/ArduinoIoTCloud_Travis_CI/thingProperties.h
Labels: type: imperfection, topic: documentation
