Repository arduino-libraries/ArduinoIoTCloud, pull requests merged in 2025-05, with the labels that each got.

#546 Standardize license file
  LICENSE
  README.md
Labels: type: enhancement, topic: documentation, topic: infrastructure

#545 Removing copyCBORStringToArray and copyCBORStringToArray functions
  extras/test/CMakeLists.txt
  extras/test/src/test_command_decode.cpp
  src/cbor/IoTCloudMessageDecoder.cpp
Labels: type: enhancement, topic: code

#550 Fix the crash of Portenta H7 with cellular connectivity
  src/ArduinoIoTCloudTCP.cpp
Labels: type: imperfection, topic: code
